package com.vegadvisor.server.persistence.bo;

import org.apache.commons.lang.exception.ExceptionUtils;

import com.vegadvisor.server.persistence.DAOException;
import com.vegadvisor.server.persistence.dao.IUsmusuarDAO;
import com.vegadvisor.server.utils.Constants;
import com.vegadvisor.server.utils.LogLogger;
import com.vegadvisor.server.utils.SpringAppContext;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

/**
 * Chdmensa generated by hbm2java
 */
public class Chdmensa implements java.io.Serializable, AbstractBO<ChdmensaId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ChdmensaId id;
	private String mchmensaf;
	private String mchientsf;
	// Nombre del usuario que ha enviado el mensaje
	private String senderName;

	public Chdmensa() {
	}

	public Chdmensa(ChdmensaId id, String mchmensaf, String mchientsf) {
		this.id = id;
		this.mchmensaf = mchmensaf;
		this.mchientsf = mchientsf;
	}

	public ChdmensaId getId() {
		return this.id;
	}

	public void setId(ChdmensaId id) {
		this.id = id;
	}

	public String getMchmensaf() {
		return this.mchmensaf;
	}

	public void setMchmensaf(String mchmensaf) {
		this.mchmensaf = mchmensaf;
	}

	public String getMchientsf() {
		return this.mchientsf;
	}

	public void setMchientsf(String mchientsf) {
		this.mchientsf = mchientsf;
	}

	/**
	 * @return the senderName
	 */
	public String getSenderName() {
		return senderName;
	}

	/**
	 * @param senderName
	 *            the senderName to set
	 */
	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	@Override
	public ChdmensaId getPrimaryKey() {
		return id;
	}

	@Override
	public void cleanObject() {
		try {
			// Crea dao de usuario
			IUsmusuarDAO usmusuarDao = SpringAppContext.getAppContext()
					.getBean(IUsmusuarDAO.class);
			// obtiene nombre de la persona que envia el mensaje
			Usmusuar sender = usmusuarDao.findById(id.getUsucusuak());
			// Asigna nombre
			senderName = sender.getUsunusuaf() + Constants.BLANK_SPACE
					+ sender.getUsuapelaf();
		} catch (DAOException e) {/* Ocurrio error */
			LogLogger.getInstance(this.getClass()).logger(
					ExceptionUtils.getFullStackTrace(e), LogLogger.ERROR);
		}

	}
}
