package com.vegadvisor.server.persistence.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Esmestab generated by hbm2java
 */
public class Esmestab implements java.io.Serializable {

	private Integer estcestnk;
	private String usucusuak;
	private String estnestaf;
	private int tesctesnk;
	private String estdireaf;
	private String estteleaf;
	private Date esthoratf;
	private Date esthorctf;
	private String paicpaiak;
	private String ciucciuak;
	private long estlatinf;
	private long estlongnf;
	private String estdestaf;
	private long estpestnf;
	private String estiactsf;

	public Esmestab() {
	}

	public Esmestab(String usucusuak, String estnestaf, int tesctesnk,
			String estdireaf, String estteleaf, Date esthoratf, Date esthorctf,
			String paicpaiak, String ciucciuak, long estlatinf, long estlongnf,
			String estdestaf, long estpestnf, String estiactsf) {
		this.usucusuak = usucusuak;
		this.estnestaf = estnestaf;
		this.tesctesnk = tesctesnk;
		this.estdireaf = estdireaf;
		this.estteleaf = estteleaf;
		this.esthoratf = esthoratf;
		this.esthorctf = esthorctf;
		this.paicpaiak = paicpaiak;
		this.ciucciuak = ciucciuak;
		this.estlatinf = estlatinf;
		this.estlongnf = estlongnf;
		this.estdestaf = estdestaf;
		this.estpestnf = estpestnf;
		this.estiactsf = estiactsf;
	}

	public Integer getEstcestnk() {
		return this.estcestnk;
	}

	public void setEstcestnk(Integer estcestnk) {
		this.estcestnk = estcestnk;
	}

	public String getUsucusuak() {
		return this.usucusuak;
	}

	public void setUsucusuak(String usucusuak) {
		this.usucusuak = usucusuak;
	}

	public String getEstnestaf() {
		return this.estnestaf;
	}

	public void setEstnestaf(String estnestaf) {
		this.estnestaf = estnestaf;
	}

	public int getTesctesnk() {
		return this.tesctesnk;
	}

	public void setTesctesnk(int tesctesnk) {
		this.tesctesnk = tesctesnk;
	}

	public String getEstdireaf() {
		return this.estdireaf;
	}

	public void setEstdireaf(String estdireaf) {
		this.estdireaf = estdireaf;
	}

	public String getEstteleaf() {
		return this.estteleaf;
	}

	public void setEstteleaf(String estteleaf) {
		this.estteleaf = estteleaf;
	}

	public Date getEsthoratf() {
		return this.esthoratf;
	}

	public void setEsthoratf(Date esthoratf) {
		this.esthoratf = esthoratf;
	}

	public Date getEsthorctf() {
		return this.esthorctf;
	}

	public void setEsthorctf(Date esthorctf) {
		this.esthorctf = esthorctf;
	}

	public String getPaicpaiak() {
		return this.paicpaiak;
	}

	public void setPaicpaiak(String paicpaiak) {
		this.paicpaiak = paicpaiak;
	}

	public String getCiucciuak() {
		return this.ciucciuak;
	}

	public void setCiucciuak(String ciucciuak) {
		this.ciucciuak = ciucciuak;
	}

	public long getEstlatinf() {
		return this.estlatinf;
	}

	public void setEstlatinf(long estlatinf) {
		this.estlatinf = estlatinf;
	}

	public long getEstlongnf() {
		return this.estlongnf;
	}

	public void setEstlongnf(long estlongnf) {
		this.estlongnf = estlongnf;
	}

	public String getEstdestaf() {
		return this.estdestaf;
	}

	public void setEstdestaf(String estdestaf) {
		this.estdestaf = estdestaf;
	}

	public long getEstpestnf() {
		return this.estpestnf;
	}

	public void setEstpestnf(long estpestnf) {
		this.estpestnf = estpestnf;
	}

	public String getEstiactsf() {
		return this.estiactsf;
	}

	public void setEstiactsf(String estiactsf) {
		this.estiactsf = estiactsf;
	}

}
