package com.vegadvisor.server.persistence.bo;

// Generated 23-oct-2015 19:39:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Fomhilfo generated by hbm2java
 */
public class Fomhilfo implements java.io.Serializable,AbstractBO<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer hifchifnk;
	private String usucusuak;
	private Date hiffregff;
	private Date hifhoratf;
	private String hiftituaf;
	private String hifdetaaf;
	private Date hiffecuff;

	public Fomhilfo() {
	}

	public Fomhilfo(String usucusuak, Date hiffregff, Date hifhoratf,
			String hiftituaf, String hifdetaaf, Date hiffecuff) {
		this.usucusuak = usucusuak;
		this.hiffregff = hiffregff;
		this.hifhoratf = hifhoratf;
		this.hiftituaf = hiftituaf;
		this.hifdetaaf = hifdetaaf;
		this.hiffecuff = hiffecuff;
	}

	public Integer getHifchifnk() {
		return this.hifchifnk;
	}

	public void setHifchifnk(Integer hifchifnk) {
		this.hifchifnk = hifchifnk;
	}

	public String getUsucusuak() {
		return this.usucusuak;
	}

	public void setUsucusuak(String usucusuak) {
		this.usucusuak = usucusuak;
	}

	public Date getHiffregff() {
		return this.hiffregff;
	}

	public void setHiffregff(Date hiffregff) {
		this.hiffregff = hiffregff;
	}

	public Date getHifhoratf() {
		return this.hifhoratf;
	}

	public void setHifhoratf(Date hifhoratf) {
		this.hifhoratf = hifhoratf;
	}

	public String getHiftituaf() {
		return this.hiftituaf;
	}

	public void setHiftituaf(String hiftituaf) {
		this.hiftituaf = hiftituaf;
	}

	public String getHifdetaaf() {
		return this.hifdetaaf;
	}

	public void setHifdetaaf(String hifdetaaf) {
		this.hifdetaaf = hifdetaaf;
	}

	public Date getHiffecuff() {
		return this.hiffecuff;
	}

	public void setHiffecuff(Date hiffecuff) {
		this.hiffecuff = hiffecuff;
	}

	@Override
	public Integer getPrimaryKey() {
		return hifchifnk;
	}

	@Override
	public void cleanObject() {
		
	}

}
